[package]
name = "radicle-registry-client"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"
license = "GPL-3.0-only"

[dependencies]
radicle-registry-runtime = { path = "../runtime" }
substrate-subxt = { path = "../subxt" }

env_logger = "0.7"
futures01 = { package = "futures", version = "0.1" }
futures03 = { package = "futures", version = "0.3", features = ["compat"] }
log = "0.4"
parity-scale-codec = "1.0"
tokio = "0.1"

[dependencies.frame-system]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"

[dependencies.frame-support]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"

[dependencies.pallet-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"

[dependencies.pallet-indices]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"

[dependencies.sp-io]
git = "https://github.com/paritytech/substrate"
rev = "2f1f3bd4af2c2521e32d884fbcd7ff991e5cac3c"
