[package]
name = "radicle-registry-client"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"
license = "GPL-3.0-only"

[dependencies]
radicle-registry-runtime = { path = "../runtime" }
substrate-subxt = { path = "../subxt" }

env_logger = "0.7"
futures01 = { package = "futures", version = "0.1" }
futures03 = { package = "futures", version = "0.3", features = ["compat"] }
log = "0.4"
parity-scale-codec = "1.0"
tokio = "0.1"
async-trait = "0.1"

[dependencies.paint-system]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.paint-support]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.paint-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dev-dependencies]
rand = "0.7.2"
