[package]
name = "radicle_registry_client"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"

[dependencies]
radicle_registry_runtime = { path = "../runtime" }
substrate-subxt = { path = "../subxt" }

env_logger = "0.7"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await", "compat"] }
futures01 = { package = "futures", version = "0.1" }
log = "0.4"
parity-scale-codec = "1.0"
tokio = "0.1"

[dependencies.frame-system]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"

[dependencies.frame-support]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"

[dependencies.pallet-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
