[package]
edition = "2018"
name = "radicle-registry-client"
description = "Client library to interact with Radicle Registry node"
version = "0.0.0"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
homepage = "https://github.com/radicle-dev/radicle-registry"
documentation = "https://github.com/radicle-dev/radicle-registry"
license = "GPL-3.0-only"
repository = "https://github.com/radicle-dev/radicle-registry"

[dependencies]
radicle-registry-runtime = { version = "0.0.0", path = "../runtime" }

async-trait = "0.1"
derive_more = "0.15"
env_logger = "0.7"
futures01 = { package = "futures", version = "0.1" }
futures03 = { package = "futures", version = "0.3", features = ["compat"] }
jsonrpc-core-client = { version = "14.0", features = ["ws"] }
log = "0.4"
parity-scale-codec = "1.0"
tokio = "0.1"
url = "1.7"

[dependencies.paint-system]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.paint-support]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.paint-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-rpc-api]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-rpc-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-transaction-graph]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dev-dependencies]
rand = "0.7.2"
