[package]
name = "radicle_registry_runtime"
authors = ["Anonymous"]
edition = "2018"
version = "0.1.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "paint-grandpa/std",
    "serde",
    "sr-primitives/std",
    "sr-io/std",
    "sr-std/std",
    "sr-version/std",
    "paint-aura/std",
    "paint-balances/std",
    "paint-executive/std",
    "paint-sudo/std",
    "paint-support/std",
    "paint-system/std",
    "paint-timestamp/std",
    "paint-transaction-payment/std",
    "sr-api/std",
    "substrate-block-builder-runtime-api/std",
    "substrate-consensus-aura-primitives/std",
    "substrate-offchain-primitives/std",
    "substrate-primitives/std",
    "substrate-session/std",
    "substrate-transaction-pool-runtime-api/std",
]

[dependencies.codec]
default-features = false
features = ["derive", "full"]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.101"

[dependencies.paint-aura]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.substrate-consensus-aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.paint-balances]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.sr-api]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.paint-executive]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "paint-executive"
default_features = false

[dependencies.substrate-offchain-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.sr-std]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.paint-randomness-collective-flip]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.substrate-session]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.substrate-block-builder-runtime-api]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.substrate-transaction-pool-runtime-api]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.substrate-inherents]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default-features = false

[dependencies.paint-sudo]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "paint-sudo"
default_features = false

[dependencies.paint-support]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.paint-system]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.paint-timestamp]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.paint-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.sr-version]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false

[dependencies.paint-grandpa]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
default_features = false
package = "paint-grandpa"

[build-dependencies]
substrate-wasm-builder-runner = "1.0.2"

[dev-dependencies]
futures = "0.1"
rand = "0.7.2"
radicle_registry_client = { path = "../client" }
