[package]
name = "radicle_registry_runtime"
authors = ["Anonymous"]
edition = "2018"
version = "0.1.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "sr-primitives/std",
    "sr-io/std",
    "sr-std/std",
    "sr-version/std",
    "pallet-aura/std",
    "pallet-balances/std",
    "frame-executive/std",
    "pallet-sudo/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "sr-api/std",
    "substrate-block-builder-runtime-api/std",
    "substrate-consensus-aura-primitives/std",
    "substrate-offchain-primitives/std",
    "substrate-primitives/std",
    "substrate-session/std",
    "substrate-transaction-pool-runtime-api/std",
]

[dependencies.codec]
default-features = false
features = ["derive", "full"]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.101"

[dependencies.pallet-aura]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.substrate-consensus-aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.pallet-balances]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.sr-api]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.frame-executive]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
package = "frame-executive"
default_features = false

[dependencies.substrate-offchain-primitives]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.sr-std]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.pallet-randomness-collective-flip]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.substrate-session]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.substrate-block-builder-runtime-api]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.substrate-transaction-pool-runtime-api]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.substrate-inherents]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default-features = false

[dependencies.pallet-sudo]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
package = "pallet-sudo"
default_features = false

[dependencies.frame-support]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.frame-system]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.pallet-timestamp]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.pallet-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[dependencies.sr-version]
git = "https://github.com/paritytech/substrate"
rev = "b9e7f09a675b5625cc8b156848d976592e07a409"
default_features = false

[build-dependencies]
substrate-wasm-builder-runner = "1.0.2"

[dev-dependencies]
futures = "0.1"
radicle_registry_client = { path = "../client" }
