.test: &test
  label: "Test"
  command: "ci/run"
  timeout_in_minutes: 60
  env:
    DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/ci-base:2020.02.10
    DOCKER_FILE: ci/base-image/Dockerfile
    STEP_DOCKER_FILE: ci/node-image/Dockerfile
    STEP_DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/node
    SHARED_MASTER_CACHE: true
  agents:
    platform: "linux"
    production: "true"
  artifact_paths:
    - "artifacts/radicle-registry-node"

steps:
  - branches: master
    concurrency: 1
    concurrency_group: master
    <<: *test
  - branches: "!master"
    <<: *test
  - wait
  - label: "Deploy"
    branches: master
    command: "ci/deploy"
    env:
      DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/ci-base@sha256:43990b4482544a2056cb61409d7e3171e4b67a2418323eab2fbd0844cad0c29c
    agents:
      platform: "linux"
      production: "true"
