steps:
  - label: "Check formatting, lint, build and test "
    command: 'ci/run'
    env:
      DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry@sha256:14f86dacda303f96b14cb1e41dc2e54be70f89ee6917920dd58207239a405f17
      DOCKER_FILE: ci/base-image/Dockerfile
    agents:
      platform: "linux"
      production: "true"
    # See https://buildkite.com/docs/pipelines/artifacts for how to download
    # the produced artifacts with Buildkite's agent CLI.
    # To download artifacts without the `buildkite-agent` tool (which only
    # works during running builds), see
    # https://buildkite.com/docs/apis/rest-api/artifacts#download-an-artifact.
    artifact_paths:
      - "artifacts/radicle-registry-node"
