env:
  DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/ci-base:c068afc4d2012cd70a9943ead3671e2e5b35508a
  DOCKER_FILE: ci/base-image/Dockerfile

.test: &test
  label: "Test"
  command: "ci/run"
  timeout_in_minutes: 60
  env:
    STEP_DOCKER_FILE: ci/node-image/Dockerfile
    STEP_DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/node
    SHARED_MASTER_CACHE: true
  artifact_paths:
    - "artifacts/*"
  agents:
    platform: "linux"
    production: "true"

.fixup: &fixup
  label: "Check fixup commits"
  command: ci/check-fixup-commits
  agents:
    platform: "linux"
    production: "true"

steps:
  - branches: master
    concurrency: 1
    concurrency_group: master
    <<: *test
  - branches: "!master"
    <<: *test
  - *fixup
  - wait
  - label: "Deploy"
    branches: master
    command: "ci/deploy"
    env:
      DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/ci-base@sha256:43990b4482544a2056cb61409d7e3171e4b67a2418323eab2fbd0844cad0c29c
    agents:
      platform: "linux"
      production: "true"

notify:
  - email: "registry-devs@monadic.xyz"
    if: |
      build.state == "failed" && build.branch == "master"
