steps:
  - label: "Check formatting, lint, build and test "
    command: 'ci/run'
    env:
      DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/ci-base@sha256:43990b4482544a2056cb61409d7e3171e4b67a2418323eab2fbd0844cad0c29c
      STEP_DOCKER_FILE: ci/node-image/Dockerfile
      STEP_DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry/node
    agents:
      platform: "linux"
      production: "true"
    # See https://buildkite.com/docs/pipelines/artifacts for how to download
    # the produced artifacts with Buildkite's agent CLI.
    # To download artifacts without the `buildkite-agent` tool (which only
    # works during running builds), see
    # https://buildkite.com/docs/apis/rest-api/artifacts#download-an-artifact.
    artifact_paths:
      - "artifacts/radicle-registry-node"
