[package]
name = "radicle-registry-cli"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"
license = "GPL-3.0-only"

[dependencies]
radicle-registry-client = { path = "../client" }

futures01 = { package = "futures", version = "0.1" }
pretty_env_logger = "0.3.1"
structopt = "0.3"
