[package]
edition = "2018"
name = "radicle-registry-cli"
description = "CLI tools for interacting with the Radicle Registry"
version = "0.0.0"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
homepage = "https://github.com/radicle-dev/radicle-registry"
documentation = "https://github.com/radicle-dev/radicle-registry"
license = "GPL-3.0-only"
repository = "https://github.com/radicle-dev/radicle-registry"

[dependencies]
radicle-registry-client = { path = "../client" }

futures01 = { package = "futures", version = "0.1" }
pretty_env_logger = "0.3.1"
structopt = "0.3"
url = "1.7"
