[package]
edition = "2018"
name = "radicle-registry-node"
description = "Full node for the Radicle Registry network"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
version = "0.0.0"
license = "GPL-3.0-only"
homepage = "https://github.com/radicle-dev/radicle-registry"
documentation = "https://github.com/radicle-dev/radicle-registry"
repository = "https://github.com/radicle-dev/radicle-registry"

[dependencies]
radicle-registry-runtime = { version = "0.0.0", path = "../runtime" }

derive_more = "0.15.0"
exit-future = "0.1.4"
futures = "0.3.1"
log = "0.4.8"
parking_lot = "0.9.0"
tokio = { version = "0.2", features = ["rt-threaded"] }
trie-root = "0.15.2"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.3"

[dependencies.sc-consensus-aura]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-consensus-aura]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-basic-authority]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-inherents]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-network]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-io]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-cli]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-client]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-executor]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-service]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-transaction-pool]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-transaction-pool]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sc-finality-grandpa]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-finality-grandpa]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"

[dependencies.sp-consensus]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"
