[package]
edition = "2018"
name = "radicle-registry-node"
description = "Full node for the Radicle Registry network"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
version = "0.0.0"
license = "GPL-3.0-only"
homepage = "https://github.com/radicle-dev/radicle-registry"
documentation = "https://github.com/radicle-dev/radicle-registry"
repository = "https://github.com/radicle-dev/radicle-registry"

[dependencies]
radicle-registry-runtime = { version = "0.0.0", path = "../runtime" }

derive_more = "0.15.0"
exit-future = "0.1.4"
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1" }
log = "0.4.8"
parking_lot = "0.9.0"
tokio = "0.1.22"
trie-root = "0.15.2"
# substrate-cli requires we fix this version
structopt = "=0.3.4"
structopt-derive = "=0.3.4"

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.3"

[dependencies.aura]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "substrate-consensus-aura"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "substrate-consensus-aura-primitives"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "substrate-basic-authorship"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "substrate-inherents"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "substrate-network"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "substrate-primitives"

[dependencies.substrate-consensus-common]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "sc-transaction-pool"

[dependencies.transaction-pool-api]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
package = "sp-transaction-pool-api"

[dependencies.substrate-finality-grandpa]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"

[dependencies.substrate-finality-grandpa-primitives]
git = "https://github.com/paritytech/substrate"
rev = "1903f36f7bafea45eababfda9011a239b3aaab6c"
