[package]
name = "radicle-registry-node"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
edition = "2018"
version = "0.1.0"
license = "GPL-3.0-only"

[dependencies]
derive_more = "0.15.0"
exit-future = "0.1.4"
futures = "0.1.29"
log = "0.4.8"
parking_lot = "0.9.0"
tokio = "0.1.22"
trie-root = "0.15.2"

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.3"

[dependencies.radicle-registry-runtime]
path = "../runtime"

[dependencies.aura]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-consensus-aura"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-consensus-aura-primitives"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-basic-authorship"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-inherents"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-network"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-primitives"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
package = "substrate-transaction-pool"

[dependencies.substrate-finality-grandpa]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"

[dependencies.substrate-finality-grandpa-primitives]
git = "https://github.com/paritytech/substrate"
rev = "dc4a8329b9c47790c25429a5df272b3648275c1b"
